import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  page: {
    width: "100%",
    fontFamily: '"Albert Sans", Inter, ui-sans-serif, system-ui, sans-serif',
    color: "#eafff6",
  },
  hero: {
    minHeight: "100svh",
    position: "relative",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    overflow: "hidden",
    padding: "clamp(24px, 4vw, 64px)",
    backgroundColor: "#03040c",
  },
  heroTop: {
    position: "relative",
    zIndex: 3,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "20px",
    color: "rgba(234,255,246,0.72)",
    fontSize: "clamp(10px, 0.9vw, 13px)",
    fontWeight: 700,
    letterSpacing: "0.25em",
    textTransform: "uppercase",
  },
  brand: { display: "flex", alignItems: "center", color: "inherit", textDecoration: "none" },
  dot: {
    width: "8px",
    height: "8px",
    flex: "0 0 auto",
    marginRight: "10px",
    borderRadius: "50%",
    backgroundColor: "#7cffb2",
    boxShadow: "0 0 14px #7cffb2",
  },
  heroNav: {
    display: "flex",
    alignItems: "center",
    gap: "24px",
    "@media (max-width: 640px)": { gap: "12px" },
  },
  heroLink: {
    color: "inherit",
    textDecoration: "none",
    transition: "color 160ms ease",
    ":hover": { color: "#eafff6" },
  },
  hideMobile: { "@media (max-width: 640px)": { display: "none" } },
  heroBottom: {
    position: "relative",
    zIndex: 3,
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: "5vw",
    "@media (max-width: 720px)": { alignItems: "flex-start", flexDirection: "column", gap: "28px" },
  },
  title: {
    margin: 0,
    fontSize: "clamp(58px, 11vw, 168px)",
    fontWeight: 820,
    letterSpacing: "-0.065em",
    lineHeight: 0.82,
    textShadow: "0 0 45px rgba(124,255,178,0.1)",
  },
  titleThin: { fontWeight: 280 },
  heroMeta: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    gap: "24px",
    paddingBottom: "4px",
    "@media (max-width: 720px)": { alignItems: "flex-start" },
  },
  subtitle: {
    maxWidth: "42ch",
    margin: 0,
    color: "rgba(234,255,246,0.78)",
    fontSize: "clamp(14px, 1.35vw, 18px)",
    lineHeight: 1.55,
  },
  heroButton: {
    display: "inline-flex",
    alignItems: "center",
    gap: "10px",
    padding: "11px 17px",
    border: "1px solid rgba(234,255,246,0.26)",
    borderRadius: "999px",
    backgroundColor: "rgba(7,12,24,0.22)",
    backdropFilter: "blur(10px)",
    color: "rgba(234,255,246,0.85)",
    textDecoration: "none",
    fontSize: "10px",
    fontWeight: 750,
    letterSpacing: "0.2em",
    textTransform: "uppercase",
    transition: "background-color 180ms ease, border-color 180ms ease",
    ":hover": { backgroundColor: "rgba(124,255,178,0.1)", borderColor: "rgba(124,255,178,0.52)" },
  },
  content: {
    maxWidth: "1240px",
    margin: "0 auto",
    padding: "clamp(72px, 9vw, 128px) clamp(18px, 4vw, 44px)",
  },
  intro: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1.1fr) minmax(280px, 0.9fr)",
    gap: "clamp(36px, 8vw, 110px)",
    alignItems: "end",
    marginBottom: "90px",
    "@media (max-width: 760px)": { gridTemplateColumns: "1fr", marginBottom: "64px" },
  },
  kicker: {
    margin: "0 0 16px",
    color: "#79e5b7",
    fontSize: "10px",
    fontWeight: 800,
    letterSpacing: "0.26em",
    textTransform: "uppercase",
  },
  sectionTitle: {
    margin: 0,
    color: "#effff8",
    fontSize: "clamp(36px, 5.2vw, 68px)",
    fontWeight: 650,
    letterSpacing: "-0.055em",
    lineHeight: 0.98,
  },
  introCopy: { margin: 0, color: "#8aa09a", fontSize: "14px", lineHeight: 1.8 },
  stack: {
    display: "grid",
    gridTemplateColumns: "repeat(4, 1fr)",
    marginBottom: "110px",
    borderTop: "1px solid rgba(194,239,224,0.13)",
    borderBottom: "1px solid rgba(194,239,224,0.13)",
    "@media (max-width: 720px)": { gridTemplateColumns: "repeat(2, 1fr)", marginBottom: "76px" },
  },
  stackItem: {
    minHeight: "132px",
    padding: "25px 22px",
    borderRight: "1px solid rgba(194,239,224,0.13)",
    ":last-child": { borderRight: 0 },
    "@media (max-width: 720px)": { borderBottom: "1px solid rgba(194,239,224,0.13)" },
  },
  stackNumber: {
    margin: "0 0 26px",
    color: "#59726a",
    fontSize: "9px",
    fontWeight: 800,
    letterSpacing: "0.15em",
  },
  stackName: { margin: 0, color: "#dff7ee", fontSize: "15px", fontWeight: 700 },
  stackDetail: { margin: "6px 0 0", color: "#647a73", fontSize: "10px", lineHeight: 1.5 },
  section: { marginTop: "96px", scrollMarginTop: "24px" },
  sectionHeader: {
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: "28px",
    marginBottom: "26px",
  },
  sectionHeading: {
    margin: 0,
    color: "#effff8",
    fontSize: "clamp(26px, 3vw, 38px)",
    fontWeight: 600,
    letterSpacing: "-0.04em",
  },
  sectionMeta: {
    color: "#637770",
    fontSize: "9px",
    fontWeight: 750,
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    "@media (max-width: 600px)": { display: "none" },
  },
  workspaceGrid: {
    display: "grid",
    gridTemplateColumns: "minmax(280px, 0.7fr) minmax(0, 1.3fr)",
    gap: "16px",
    "@media (max-width: 840px)": { gridTemplateColumns: "1fr" },
  },
  panel: {
    overflow: "hidden",
    border: "1px solid rgba(194,239,224,0.11)",
    borderRadius: "4px",
    backgroundColor: "rgba(7,12,19,0.72)",
    boxShadow: "inset 0 1px rgba(255,255,255,0.025)",
  },
  panelHeader: {
    minHeight: "55px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    padding: "0 19px",
    borderBottom: "1px solid rgba(194,239,224,0.09)",
  },
  panelTitle: {
    margin: 0,
    color: "#dff7ee",
    fontSize: "11px",
    fontWeight: 750,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  panelMeta: {
    color: "#52665f",
    fontSize: "8px",
    fontWeight: 700,
    letterSpacing: "0.12em",
    textTransform: "uppercase",
  },
  form: { display: "grid", gap: "16px", padding: "21px" },
  label: {
    display: "grid",
    gap: "8px",
    color: "#71877f",
    fontSize: "9px",
    fontWeight: 750,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  input: {
    width: "100%",
    minHeight: "43px",
    padding: "0 12px",
    border: "1px solid rgba(194,239,224,0.12)",
    borderRadius: "3px",
    outline: "none",
    backgroundColor: "rgba(2,5,11,0.68)",
    color: "#eafff6",
    fontSize: "12px",
    letterSpacing: 0,
    textTransform: "none",
    transition: "border-color 160ms ease, box-shadow 160ms ease",
    ":focus": {
      borderColor: "rgba(124,255,178,0.55)",
      boxShadow: "0 0 0 3px rgba(124,255,178,0.06)",
    },
  },
  button: {
    minHeight: "43px",
    border: "1px solid rgba(124,255,178,0.45)",
    borderRadius: "3px",
    backgroundColor: "rgba(124,255,178,0.1)",
    color: "#aaffc9",
    fontSize: "9px",
    fontWeight: 800,
    letterSpacing: "0.16em",
    textTransform: "uppercase",
    cursor: "pointer",
    transition: "background-color 160ms ease",
    ":hover": { backgroundColor: "rgba(124,255,178,0.17)" },
    ":disabled": { opacity: 0.5, cursor: "wait" },
  },
  error: { margin: 0, color: "#ff9ba9", fontSize: "10px" },
  tableWrap: { overflowX: "auto" },
  table: { width: "100%", borderCollapse: "collapse", fontSize: "11px" },
  tableHead: {
    color: "#587068",
    textAlign: "left",
    fontSize: "8px",
    fontWeight: 800,
    letterSpacing: "0.14em",
    textTransform: "uppercase",
  },
  tableCell: { padding: "18px 19px", borderBottom: "1px solid rgba(194,239,224,0.075)" },
  pluginGrid: {
    display: "grid",
    gridTemplateColumns: "minmax(260px, 0.72fr) minmax(0, 1.28fr)",
    gap: "16px",
    "@media (max-width: 800px)": { gridTemplateColumns: "1fr" },
  },
  selectedPanel: {
    minHeight: "380px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    padding: "26px",
    border: "1px solid rgba(194,239,224,0.11)",
    borderRadius: "4px",
    background:
      "radial-gradient(circle at 80% 10%, rgba(70,180,140,0.12), transparent 38%), rgba(7,12,19,0.72)",
  },
  selectedIcon: {
    width: "42px",
    height: "42px",
    display: "grid",
    placeItems: "center",
    border: "1px solid rgba(124,255,178,0.28)",
    borderRadius: "50%",
    color: "#8affe0",
    fontSize: "10px",
    fontWeight: 850,
    letterSpacing: "0.08em",
  },
  selectedLabel: {
    margin: "0 0 10px",
    color: "#66877c",
    fontSize: "8px",
    fontWeight: 800,
    letterSpacing: "0.2em",
    textTransform: "uppercase",
  },
  pluginName: { margin: 0, color: "#e5fff5", fontSize: "14px", fontWeight: 750 },
  selectedName: {
    margin: 0,
    color: "#edfff8",
    fontSize: "clamp(25px, 3vw, 34px)",
    fontWeight: 580,
    letterSpacing: "-0.04em",
  },
  pluginText: { margin: "6px 0 0", color: "#688078", fontSize: "10px", lineHeight: 1.55 },
  selectedText: { margin: "12px 0 0", color: "#8ba099", fontSize: "12px", lineHeight: 1.7 },
  virtualScroller: {
    height: "380px",
    overflowY: "auto",
    border: "1px solid rgba(194,239,224,0.11)",
    borderRadius: "4px",
    backgroundColor: "rgba(7,12,19,0.72)",
    scrollbarColor: "#29443a transparent",
  },
  virtualItem: {
    width: "100%",
    minHeight: "76px",
    display: "grid",
    gridTemplateColumns: "40px 1fr 18px",
    alignItems: "center",
    gap: "13px",
    padding: "12px 16px",
    borderBottom: "1px solid rgba(194,239,224,0.075)",
    backgroundColor: "transparent",
    cursor: "pointer",
    transition: "background-color 150ms ease",
    ":hover": { backgroundColor: "rgba(124,255,178,0.035)" },
  },
  virtualItemSelected: { backgroundColor: "rgba(124,255,178,0.06)" },
  pluginIcon: {
    width: "38px",
    height: "38px",
    display: "grid",
    placeItems: "center",
    border: "1px solid rgba(194,239,224,0.12)",
    borderRadius: "50%",
    color: "#718e84",
    fontSize: "9px",
    fontWeight: 850,
  },
  arrow: { color: "#476159", fontSize: "14px" },
  footer: {
    display: "flex",
    justifyContent: "space-between",
    gap: "16px",
    marginTop: "100px",
    paddingTop: "22px",
    borderTop: "1px solid rgba(194,239,224,0.1)",
    color: "#4e645d",
    fontSize: "8px",
    fontWeight: 750,
    letterSpacing: "0.18em",
    textTransform: "uppercase",
  },
});
