import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  page: {
    maxWidth: "1120px",
    margin: "0 auto",
    padding: "32px 20px 72px",
    fontFamily: "Inter, ui-sans-serif, system-ui, sans-serif",
    color: "#e7eaf3",
  },
  header: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    marginBottom: "32px",
  },
  eyebrow: {
    fontSize: "13px",
    fontWeight: 700,
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    color: "#8b9df7",
  },
  title: {
    margin: 0,
    fontSize: "clamp(32px, 5vw, 52px)",
    lineHeight: 1.05,
    letterSpacing: "-0.035em",
  },
  subtitle: {
    margin: 0,
    maxWidth: "720px",
    fontSize: "17px",
    lineHeight: 1.6,
    color: "#a8b1c9",
  },
  section: {
    marginTop: "36px",
  },
  sectionTitle: {
    margin: "0 0 14px",
    fontSize: "20px",
    fontWeight: 700,
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
    gap: "20px",
    alignItems: "start",
  },
  card: {
    padding: "22px",
    borderRadius: "18px",
    border: "1px solid rgba(255, 255, 255, 0.09)",
    backgroundColor: "rgba(19, 23, 35, 0.82)",
    boxShadow: "0 24px 70px rgba(0, 0, 0, 0.26)",
  },
  form: {
    display: "grid",
    gap: "14px",
  },
  label: {
    display: "grid",
    gap: "7px",
    fontSize: "13px",
    fontWeight: 650,
    color: "#a8b1c9",
  },
  input: {
    borderRadius: "10px",
    border: "1px solid rgba(255, 255, 255, 0.12)",
    backgroundColor: "rgba(9, 11, 18, 0.9)",
    color: "#f3f5fb",
    padding: "11px 12px",
    fontSize: "15px",
  },
  button: {
    borderRadius: "10px",
    border: "0",
    backgroundColor: "#6674f2",
    color: "white",
    fontSize: "15px",
    fontWeight: 700,
    padding: "11px 16px",
    cursor: "pointer",
  },
  buttonDisabled: {
    opacity: 0.55,
    cursor: "not-allowed",
  },
  status: {
    margin: 0,
    fontSize: "13px",
    color: "#a8b1c9",
  },
  error: {
    margin: 0,
    fontSize: "13px",
    fontWeight: 600,
    color: "#ff9a9e",
  },
  tableWrap: {
    overflowX: "auto",
    borderRadius: "16px",
    border: "1px solid rgba(255, 255, 255, 0.09)",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: "14px",
  },
  tableHead: {
    textAlign: "left",
    backgroundColor: "rgba(33, 39, 57, 0.9)",
    color: "#a8b1c9",
    fontSize: "12px",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  },
  tableCell: {
    padding: "13px 14px",
    borderBottom: "1px solid rgba(255, 255, 255, 0.07)",
  },
  virtualScroller: {
    height: "380px",
    overflowY: "auto",
    borderRadius: "16px",
    border: "1px solid rgba(255, 255, 255, 0.09)",
    backgroundColor: "rgba(12, 15, 23, 0.8)",
  },
  virtualItem: {
    display: "grid",
    gap: "5px",
    width: "100%",
    padding: "14px 16px",
    borderBottom: "1px solid rgba(255, 255, 255, 0.07)",
    backgroundColor: "#131723",
  },
  virtualItemSelected: {
    backgroundColor: "#202741",
  },
  pluginName: {
    margin: 0,
    fontSize: "15px",
    fontWeight: 750,
  },
  pluginText: {
    margin: 0,
    fontSize: "13px",
    lineHeight: 1.5,
    color: "#a8b1c9",
  },
  selectedPanel: {
    padding: "16px",
    borderRadius: "14px",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    backgroundColor: "rgba(31, 38, 58, 0.85)",
  },
});
